
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        mainLoginPanel.setVisible(true);
        mainLandlordGUI.setVisible(false);
        mainRegisteredGUI.setVisible(false);
        mainUnregisteredGUI.setVisible(false);
        registeredRenterLoginPanel.setVisible(false);
        landlordLoginPanel.setVisible(false);
        renterLoginPanel.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginAsRenterButton = new javax.swing.JButton();
        loginAsLandlordButton = new javax.swing.JButton();
        mainUnregisteredGUI = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        mainRegisteredGUI = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        mainLandlordGUI = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        registeredRenterLoginPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        submitRenterLoginButton = new javax.swing.JButton();
        backToMainLoginFromRegisteredRenterButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        renterUsernameTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        renterPasswordTextArea = new javax.swing.JTextArea();
        landlordLoginPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        submitLandlordLoginButton = new javax.swing.JButton();
        backToMainLoginFromLandlordButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        landlordUsernameTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        landlordPasswordTextArea = new javax.swing.JTextArea();
        renterLoginPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        continueAsUnregisteredButton = new javax.swing.JButton();
        loginAsRegisteredButton = new javax.swing.JButton();
        backToMainLoginFromRenterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLoginPanel.setBackground(new java.awt.Color(204, 255, 255));
        mainLoginPanel.setMinimumSize(new java.awt.Dimension(850, 475));

        jLabel1.setText("Property Rental Application - Main Login");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        loginAsRenterButton.setBackground(new java.awt.Color(102, 204, 255));
        loginAsRenterButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginAsRenterButton.setText("Login as Renter");
        loginAsRenterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginAsRenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsRenterButtonActionPerformed(evt);
            }
        });

        loginAsLandlordButton.setBackground(new java.awt.Color(153, 255, 153));
        loginAsLandlordButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginAsLandlordButton.setText("Login as Landlord");
        loginAsLandlordButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginAsLandlordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsLandlordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLoginPanelLayout = new javax.swing.GroupLayout(mainLoginPanel);
        mainLoginPanel.setLayout(mainLoginPanelLayout);
        mainLoginPanelLayout.setHorizontalGroup(
                mainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainLoginPanelLayout.createSequentialGroup()
                                                .addComponent(loginAsRenterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addComponent(loginAsLandlordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        mainLoginPanelLayout.setVerticalGroup(
                mainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(mainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loginAsRenterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                                        .addComponent(loginAsLandlordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        jLabel11.setText("Unregistered Renter");

        javax.swing.GroupLayout mainUnregisteredGUILayout = new javax.swing.GroupLayout(mainUnregisteredGUI);
        mainUnregisteredGUI.setLayout(mainUnregisteredGUILayout);
        mainUnregisteredGUILayout.setHorizontalGroup(
                mainUnregisteredGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainUnregisteredGUILayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainUnregisteredGUILayout.setVerticalGroup(
                mainUnregisteredGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainUnregisteredGUILayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel10.setText("Registered Renter");

        javax.swing.GroupLayout mainRegisteredGUILayout = new javax.swing.GroupLayout(mainRegisteredGUI);
        mainRegisteredGUI.setLayout(mainRegisteredGUILayout);
        mainRegisteredGUILayout.setHorizontalGroup(
                mainRegisteredGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainRegisteredGUILayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainRegisteredGUILayout.setVerticalGroup(
                mainRegisteredGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainRegisteredGUILayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel9.setText("Landlord");

        javax.swing.GroupLayout mainLandlordGUILayout = new javax.swing.GroupLayout(mainLandlordGUI);
        mainLandlordGUI.setLayout(mainLandlordGUILayout);
        mainLandlordGUILayout.setHorizontalGroup(
                mainLandlordGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainLandlordGUILayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        mainLandlordGUILayout.setVerticalGroup(
                mainLandlordGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainLandlordGUILayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addContainerGap(64, Short.MAX_VALUE))
        );

        registeredRenterLoginPanel.setBackground(new java.awt.Color(204, 204, 255));
        registeredRenterLoginPanel.setMinimumSize(new java.awt.Dimension(350, 175));

        jLabel6.setText("Registered Renter Login");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        submitRenterLoginButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitRenterLoginButton.setText("Submit");
        submitRenterLoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitRenterLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRenterLoginButtonActionPerformed(evt);
            }
        });

        backToMainLoginFromRegisteredRenterButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backToMainLoginFromRegisteredRenterButton.setText("Back");
        backToMainLoginFromRegisteredRenterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backToMainLoginFromRegisteredRenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainLoginFromRegisteredRenterButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Username");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        renterUsernameTextArea.setColumns(20);
        renterUsernameTextArea.setRows(5);
        jScrollPane3.setViewportView(renterUsernameTextArea);

        jLabel8.setText("Password");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        renterPasswordTextArea.setColumns(20);
        renterPasswordTextArea.setRows(5);
        jScrollPane4.setViewportView(renterPasswordTextArea);

        javax.swing.GroupLayout registeredRenterLoginPanelLayout = new javax.swing.GroupLayout(registeredRenterLoginPanel);
        registeredRenterLoginPanel.setLayout(registeredRenterLoginPanelLayout);
        registeredRenterLoginPanelLayout.setHorizontalGroup(
                registeredRenterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registeredRenterLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(registeredRenterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registeredRenterLoginPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane3))
                                        .addGroup(registeredRenterLoginPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                                        .addGroup(registeredRenterLoginPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(registeredRenterLoginPanelLayout.createSequentialGroup()
                                                .addComponent(backToMainLoginFromRegisteredRenterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(submitRenterLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        registeredRenterLoginPanelLayout.setVerticalGroup(
                registeredRenterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registeredRenterLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registeredRenterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registeredRenterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(registeredRenterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(submitRenterLoginButton)
                                        .addComponent(backToMainLoginFromRegisteredRenterButton))
                                .addContainerGap())
        );

        landlordLoginPanel.setBackground(new java.awt.Color(153, 255, 153));
        landlordLoginPanel.setMinimumSize(new java.awt.Dimension(350, 175));

        jLabel3.setText("Landlord Login");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        submitLandlordLoginButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitLandlordLoginButton.setText("Submit");
        submitLandlordLoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitLandlordLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLandlordLoginButtonActionPerformed(evt);
            }
        });

        backToMainLoginFromLandlordButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backToMainLoginFromLandlordButton.setText("Back");
        backToMainLoginFromLandlordButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backToMainLoginFromLandlordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainLoginFromLandlordButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Username");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        landlordUsernameTextArea.setColumns(20);
        landlordUsernameTextArea.setRows(5);
        jScrollPane1.setViewportView(landlordUsernameTextArea);

        jLabel5.setText("Password");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        landlordPasswordTextArea.setColumns(20);
        landlordPasswordTextArea.setRows(5);
        jScrollPane2.setViewportView(landlordPasswordTextArea);

        javax.swing.GroupLayout landlordLoginPanelLayout = new javax.swing.GroupLayout(landlordLoginPanel);
        landlordLoginPanel.setLayout(landlordLoginPanelLayout);
        landlordLoginPanelLayout.setHorizontalGroup(
                landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(landlordLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(landlordLoginPanelLayout.createSequentialGroup()
                                                .addComponent(backToMainLoginFromLandlordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                                .addComponent(submitLandlordLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(landlordLoginPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(landlordLoginPanelLayout.createSequentialGroup()
                                                .addGroup(landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2)
                                                        .addComponent(jScrollPane1))))
                                .addContainerGap())
        );
        landlordLoginPanelLayout.setVerticalGroup(
                landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(landlordLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(landlordLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(submitLandlordLoginButton)
                                        .addComponent(backToMainLoginFromLandlordButton))
                                .addContainerGap())
        );

        renterLoginPanel.setBackground(new java.awt.Color(153, 204, 255));
        renterLoginPanel.setMinimumSize(new java.awt.Dimension(300, 200));

        jLabel2.setText("Renter Login ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        continueAsUnregisteredButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        continueAsUnregisteredButton.setText("Continue as Unregistered User");
        continueAsUnregisteredButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        continueAsUnregisteredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueAsUnregisteredButtonActionPerformed(evt);
            }
        });

        loginAsRegisteredButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginAsRegisteredButton.setText("Login as Registered User");
        loginAsRegisteredButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginAsRegisteredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsRegisteredButtonActionPerformed(evt);
            }
        });

        backToMainLoginFromRenterButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backToMainLoginFromRenterButton.setText("Back");
        backToMainLoginFromRenterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backToMainLoginFromRenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainLoginFromRenterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout renterLoginPanelLayout = new javax.swing.GroupLayout(renterLoginPanel);
        renterLoginPanel.setLayout(renterLoginPanelLayout);
        renterLoginPanelLayout.setHorizontalGroup(
                renterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(renterLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(renterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(continueAsUnregisteredButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(loginAsRegisteredButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(backToMainLoginFromRenterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        renterLoginPanelLayout.setVerticalGroup(
                renterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(renterLoginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(continueAsUnregisteredButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginAsRegisteredButton)
                                .addGap(11, 11, 11)
                                .addComponent(backToMainLoginFromRenterButton)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(mainUnregisteredGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(mainRegisteredGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(mainLandlordGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(registeredRenterLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(landlordLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(renterLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(mainUnregisteredGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(mainRegisteredGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(mainLandlordGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(registeredRenterLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(landlordLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(renterLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>

    private void loginAsRenterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        renterLoginPanel.setVisible(true);
        mainLoginPanel.setVisible(false);
    }

    private void loginAsLandlordButtonActionPerformed(java.awt.event.ActionEvent evt) {
        mainLoginPanel.setVisible(false);
        landlordLoginPanel.setVisible(true);
    }

    private void continueAsUnregisteredButtonActionPerformed(java.awt.event.ActionEvent evt) {
        mainUnregisteredGUI.setVisible(true);
        renterLoginPanel.setVisible(false);
    }

    private void loginAsRegisteredButtonActionPerformed(java.awt.event.ActionEvent evt) {
        registeredRenterLoginPanel.setVisible(true);
        renterLoginPanel.setVisible(false);
    }

    private void submitLandlordLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        mainLandlordGUI.setVisible(true);
        landlordLoginPanel.setVisible(false);
    }

    private void backToMainLoginFromLandlordButtonActionPerformed(java.awt.event.ActionEvent evt) {
        mainLoginPanel.setVisible(true);
        landlordLoginPanel.setVisible(false);
    }

    private void submitRenterLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        mainRegisteredGUI.setVisible(true);
        registeredRenterLoginPanel.setVisible(false);
    }

    private void backToMainLoginFromRegisteredRenterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        registeredRenterLoginPanel.setVisible(false);
        renterLoginPanel.setVisible(true);
    }

    private void backToMainLoginFromRenterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        mainLoginPanel.setVisible(true);
        renterLoginPanel.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backToMainLoginFromLandlordButton;
    private javax.swing.JButton backToMainLoginFromRegisteredRenterButton;
    private javax.swing.JButton backToMainLoginFromRenterButton;
    private javax.swing.JButton continueAsUnregisteredButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel landlordLoginPanel;
    private javax.swing.JTextArea landlordPasswordTextArea;
    private javax.swing.JTextArea landlordUsernameTextArea;
    private javax.swing.JButton loginAsLandlordButton;
    private javax.swing.JButton loginAsRegisteredButton;
    private javax.swing.JButton loginAsRenterButton;
    private javax.swing.JPanel mainLandlordGUI;
    private javax.swing.JPanel mainLoginPanel;
    private javax.swing.JPanel mainRegisteredGUI;
    private javax.swing.JPanel mainUnregisteredGUI;
    private javax.swing.JPanel registeredRenterLoginPanel;
    private javax.swing.JPanel renterLoginPanel;
    private javax.swing.JTextArea renterPasswordTextArea;
    private javax.swing.JTextArea renterUsernameTextArea;
    private javax.swing.JButton submitLandlordLoginButton;
    private javax.swing.JButton submitRenterLoginButton;
    // End of variables declaration
}
